// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://t.me/iivkis"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cookie": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Get ApiKey by cookie",
                "operationId": "FromCookie",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.AuthFromCookieOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "tags": [
                    "auth"
                ],
                "summary": "Delete cookie",
                "operationId": "DeleteCookie",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/signIn": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Sign in user profile",
                "operationId": "SignIn",
                "parameters": [
                    {
                        "description": "sign in data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.AuthSignInBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.AuthSignInOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/signUp": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Create a new user profile",
                "operationId": "SignUp",
                "parameters": [
                    {
                        "description": "sign up data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.AuthSignUpBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/answers": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Returns the created answers of the current user to the questions",
                "tags": [
                    "answers"
                ],
                "summary": "Get answers",
                "operationId": "GetAnswers",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "name": "question_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/repository.AnswerModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Create new answer for question",
                "operationId": "AddAnswer",
                "parameters": [
                    {
                        "description": "answer body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.AnswerPostBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/answers/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Get one answers by ID",
                "operationId": "GetOneAnswer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "answer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.AnswerModel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "answers"
                ],
                "summary": "Update answer fields",
                "operationId": "UpdateAnswer",
                "parameters": [
                    {
                        "description": "answer body",
                        "name": "struct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.AnswersPutBody"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "answer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/check": {
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "checking"
                ],
                "summary": "Check of correct answers",
                "operationId": "CheckingAnswers",
                "parameters": [
                    {
                        "description": "check answers body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.CheckingAnswersPostBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.CheckingAnswersPostOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/questions": {
            "get": {
                "tags": [
                    "questions"
                ],
                "summary": "Get questions",
                "operationId": "GetQuestions",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "name": "task_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/repository.QuestionModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Create a new question for task",
                "operationId": "AddQuestion",
                "parameters": [
                    {
                        "description": "question body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.QuestionsPostBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/questions/{id}": {
            "get": {
                "tags": [
                    "questions"
                ],
                "summary": "Get one question by ID",
                "operationId": "GetOneQuestion",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.QuestionModel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Update question fields",
                "operationId": "UpdateQuestion",
                "parameters": [
                    {
                        "description": "question body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.QuestionsPutBody"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/tasks": {
            "get": {
                "tags": [
                    "tasks"
                ],
                "summary": "Get tasks",
                "operationId": "GetTasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/repository.TasksFindResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Create a new task",
                "operationId": "AddTask",
                "parameters": [
                    {
                        "description": "task body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.TasksPostBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/t/tasks/{id}": {
            "get": {
                "tags": [
                    "tasks"
                ],
                "summary": "Get one task by ID",
                "operationId": "GetOneTask",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.TasksFindResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Update task fields",
                "operationId": "UpdateTask",
                "parameters": [
                    {
                        "description": "task body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrlv1.TasksPutBody"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ctrlv1.wrap"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ctrlv1.DefaultOut"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "ctrlv1.AnswerPostBody": {
            "type": "object",
            "required": [
                "question_id",
                "value"
            ],
            "properties": {
                "question_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 77
                },
                "value": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "zero"
                }
            }
        },
        "ctrlv1.AnswersPutBody": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "ctrlv1.AuthFromCookieOut": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "ctrlv1.AuthSignInBody": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "example@mail.ru"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4,
                    "example": "qwerty27"
                }
            }
        },
        "ctrlv1.AuthSignInOut": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlzcyI6ImFzdS1vbHltcCJ9.NPFZIvICrpfdqUlbr5vfvRMCHgbKj28eXmLjftWPjyc"
                }
            }
        },
        "ctrlv1.AuthSignUpBody": {
            "type": "object",
            "required": [
                "email",
                "full_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "example@mail.ru"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Фёдоров И.С."
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4,
                    "example": "qwerty27"
                }
            }
        },
        "ctrlv1.CheckingAnswersPostBody": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ctrlv1.CheckingAnswersPostBodyFieldAnswer"
                    }
                },
                "task_id": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "ctrlv1.CheckingAnswersPostBodyFieldAnswer": {
            "type": "object",
            "properties": {
                "question_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "value": {
                    "type": "string",
                    "maxLength": 1000
                }
            }
        },
        "ctrlv1.CheckingAnswersPostOut": {
            "type": "object",
            "properties": {
                "num_of_correct": {
                    "type": "integer"
                },
                "results": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "show_correct": {
                    "type": "boolean"
                },
                "task_id": {
                    "type": "integer"
                }
            }
        },
        "ctrlv1.DefaultOut": {
            "description": "Record ID",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "ctrlv1.QuestionsPostBody": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "task_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "text": {
                    "type": "string",
                    "maxLength": 1000
                }
            }
        },
        "ctrlv1.QuestionsPutBody": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "ctrlv1.TasksPostBody": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 10
                },
                "is_public": {
                    "type": "boolean"
                },
                "show_correct": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "ctrlv1.TasksPutBody": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "show_correct": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "ctrlv1.wrap": {
            "description": "Standard wrapper for responses",
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "boolean"
                }
            }
        },
        "repository.AnswerModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "question_id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "repository.QuestionModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "repository.TasksFindResult": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "author_name": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_public": {
                    "type": "boolean"
                },
                "show_correct": {
                    "type": "boolean"
                },
                "solutions_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKey": {
            "description": "JWT token for authorization",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0-alpha",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ASU-Olymp API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
